kind: Secret
apiVersion: v1
metadata:
  name: api-course-db-secret
data:
  CONNECTION_STRING: {{ .Values.secrets.apiCourseDbSecret.connectionString | b64enc }}
  PASSWORD: {{ .Values.secrets.apiCourseDbSecret.password | b64enc }}
  USERNAME: {{ .Values.secrets.apiCourseDbSecret.userName | b64enc }}
type: Opaque
