kind: Secret
apiVersion: v1
metadata:
  name: course-client-secret
data:
  COURSE_CLIENT_NAME: {{ .Values.secrets.courseClientSecret.courseClientName | b64enc }}
  COURSE_CLIENT_SECRET: {{ .Values.secrets.courseClientSecret.courseClientSecret | b64enc }}
type: Opaque