-- STUDENT_COURSE definition

CREATE TABLE "STUDENT_COURSE"
(	"STUDENT_COURSE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "COURSE_ID" NUMBER(7),
     "COURSE_CODE" VARCHAR2(7) NOT NULL ENABLE,
     "COURSE_LEVEL" VARCHAR2(3),
     "COURSE_SESSION" DATE NOT NULL ENABLE,
     "INTERIM_PERCENT" NUMBER(3),
     "INTERIM_LETTER_GRADE" VARCHAR2(2),
     "FINAL_PERCENT" NUMBER(3),
     "FINAL_LETTER_GRADE" VARCHAR2(2),
     "NUMBER_CREDITS" NUMBER(1),
     "EQUIVALENT_OR_CHALLENGE_CODE" VARCHAR2(1),
     "FINE_ARTS_APPLIED_SKILLS_CODE" VARCHAR2(1),
     "RELATED_COURSE_ID" NUMBER(7),
     "RELATED_COURSE" VARCHAR2(7),
     "RELATED_LEVEL" VARCHAR2(3),
     "CUSTOM_COURSE_NAME" VARCHAR2(40),
     "STUDENT_COURSE_EXAM_ID" RAW(16),
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "STUDENT_COURSE_PK" PRIMARY KEY ("STUDENT_COURSE_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "STUDENT_COURSE_EXAM_FK" FOREIGN KEY ("STUDENT_COURSE_EXAM_ID")
         REFERENCES "STUDENT_COURSE_EXAM" ("STUDENT_COURSE_EXAM_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;


CREATE INDEX IDX_GRADUATION_STUDENT_RECORD_ID
    ON STUDENT_COURSE ("GRADUATION_STUDENT_RECORD_ID")
    TABLESPACE "API_GRAD_IDX"