UPDATE EQUIVALENT_OR_CHALLENGE_CODE
SET LABEL='Equivalency', DESCRIPTION='Indicates that the course credit was earned through an equivalency review. ',
    EFFECTIVE_DATE=TO_DATE('1984-01-01', 'YYYY-MM-DD'), UPDATE_USER='API_COURSE' , UPDATE_DATE=SYSTIMESTAMP
WHERE EQUIVALENT_OR_CHALLENGE_CODE='E';

UPDATE EQUIVALENT_OR_CHALLENGE_CODE
SET LABEL='Challenge', DESCRIPTION='Indicates that the course credit was earned through the challenge process. ',
    EFFECTIVE_DATE=TO_DATE('1984-01-01', 'YYYY-MM-DD'), UPDATE_USER='API_COURSE' , UPDATE_DATE=SYSTIMESTAMP
WHERE EQUIVALENT_OR_CHALLENGE_CODE='C';