INSERT INTO EQUIVALENT_OR_CHALLENGE_CODE (EQUIVALENT_OR_CHALLENGE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('E','Equivalency','Course Requirement is met by an equivalency.',1,TIMESTAMP'1984-01-01 00:00:00.0',NULL);
INSERT INTO EQUIVALENT_OR_CHALLENGE_CODE (EQUIVALENT_OR_CHALLENGE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('C','Challenge','Course Requirement is met by a course challenge.',2,TIMESTAMP'1984-01-01 00:00:00.0',NULL);

