GRANT SELECT ON COURSE_REQUIREMENT_CODE TO GRAD_READONLY;
GRANT SELECT ON COURSE_REQUIREMENT TO GRAD_READONLY;
GRANT SELECT ON COURSE_RESTRICTION TO GRAD_READONLY;
GRANT SELECT ON TRAX_STUDENT_COURSES TO GRAD_READONLY;
GRANT SELECT ON TAB_CRSE TO GRAD_READONLY;
GRANT SELECT ON PROV_EXAM TO GRAD_READONLY;
GRANT SELECT ON STUD_XCRSE TO GRAD_READONLY;





