-- EQUIVALENT_OR_CHALLENGE_CODE definition

CREATE TABLE "EQUIVALENT_OR_CHALLENGE_CODE"
(	"EQUIVALENT_OR_CHALLENGE_CODE" VARCHAR2(1),
     "LABEL" VARCHAR2(50) NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(355) NOT NULL ENABLE,
     "DISPLAY_ORDER" NUMBER NOT NULL ENABLE,
     "EFFECTIVE_DATE" DATE NOT NULL ENABLE,
     "EXPIRY_DATE" DATE,
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "EQUIVALENT_OR_CHALLENGE_CODE_PK" PRIMARY KEY ("EQUIVALENT_OR_CHALLENGE_CODE")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
  