-- EXAM_SPECIAL_CASE_CODE definition

CREATE TABLE "EXAM_SPECIAL_CASE_CODE"
(	"EXAM_SPECIAL_CASE_CODE" VARCHAR2(1),
     "LABEL" VARCHAR2(50) NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(355) NOT NULL ENABLE,
     "DISPLAY_ORDER" NUMBER NOT NULL ENABLE,
     "EFFECTIVE_DATE" DATE NOT NULL ENABLE,
     "EXPIRY_DATE" DATE,
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "EXAM_SPECIAL_CASE_CODE_PK" PRIMARY KEY ("EXAM_SPECIAL_CASE_CODE")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
  