INSERT INTO FINE_ARTS_APPLIED_SKILLS_CODE (FINE_ARTS_APPLIED_SKILLS_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('A','Applied Skills','Course meets the Applied Skills Requirement',1,TIMESTAMP'1984-01-01 00:00:00.0',NULL);
INSERT INTO FINE_ARTS_APPLIED_SKILLS_CODE (FINE_ARTS_APPLIED_SKILLS_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('F','Fine Arts','Course meets the Fine Arts Requirement',2,TIMESTAMP'1984-01-01 00:00:00.0',NULL);
INSERT INTO FINE_ARTS_APPLIED_SKILLS_CODE (FINE_ARTS_APPLIED_SKILLS_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) VALUES ('B','Both','Course meets both the Applied Skills AND Fine Arts Requirement',3,TIMESTAMP'1984-01-01 00:00:00.0',NULL);

