-- COURSE_REQUIREMENT definition

CREATE TABLE "COURSE_REQUIREMENT" 
   (	"COURSE_REQUIREMENT_ID" RAW(16) DEFAULT SYS_GUID(), 
	"COURSE_CODE" VARCHAR2(7) NOT NULL ENABLE, 
	"COURSE_LEVEL" VARCHAR2(3), 
	"COURSE_REQUIREMENT_CODE" VARCHAR2(4) NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "COURSE_REQUIREMENT_PK" PRIMARY KEY ("COURSE_REQUIREMENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE, 
	 CONSTRAINT "CRSE_RQMT_CRSE_RQMTCD_FK" FOREIGN KEY ("COURSE_REQUIREMENT_CODE")
	  REFERENCES "COURSE_REQUIREMENT_CODE" ("COURSE_REQUIREMENT_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
  