UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'NME10' WHERE COURSE_REQUIREMENT_CODE = '116';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTE10' WHERE COURSE_REQUIREMENT_CODE = '115';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTE12' WHERE COURSE_REQUIREMENT_CODE = '118';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTP12' WHERE COURSE_REQUIREMENT_CODE = '304';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTF12' WHERE COURSE_REQUIREMENT_CODE = '203';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTP10' WHERE COURSE_REQUIREMENT_CODE = '303';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTE12' WHERE COURSE_REQUIREMENT_CODE = '404';
UPDATE COURSE_REQUIREMENT_CODE SET LABEL = 'LTE10' WHERE COURSE_REQUIREMENT_CODE = '403';





